name: Check Python File Permissions

on:
  push:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  check_permissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check Python File Permissions
      run: |
        find . -name '*.py' ! -executable -print
        exit 0  # Exit with success if all Python files are executable
