name: Execute Python file after Git clone

on:
  push:
    branches:
      - main

jobs:
  execute_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        # with:
        #   python-version: '3.x' # Specify the Python version you need

      - name: Make script executable
        run: chmod +x ./*.py ./*.sh

      - name: Execute Python script
        run: python ./*.py
